config/routes.rb
Chabad::Application.routes.draw do
  get "pages/performing_art_for_all"

 devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
 resources :causes
 resources :donations do
  collection do
    get 'express_paypal'    
    get 'pay'
  end  
 end

  root :to => 'home#index'

end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  before_filter :current_user_is_admin?
  layout 'admin'

  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @cause = Cause.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = Cause.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(params[:cause])

    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to causes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/views/causes/_form.html.erb
<%= form_for(@cause) do |f| %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
 <!--  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div> -->
  <%= f.hidden_field :category_id, value: "1" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<%= provide 'page-header', 'Editing cause' %>

<%= render 'form' %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

app/views/causes/index.html.erb
<%= provide 'page-header', 'Listing causes' %>

<table class='table'>
  <thead>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

<% @causes.each do |cause| %>
  <tr>
    <td><%= cause.name %></td>
    <td><%= cause.category_id %></td>
    <td><%= link_to 'Show', cause %></td>
    <td><%= link_to 'Edit', edit_cause_path(cause) %></td>
    <td><%= link_to 'Destroy', cause, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cause', new_cause_path %>

app/views/causes/new.html.erb
<%= provide 'page-header', 'New cause' %>

<%= render 'form' %>

<%= link_to 'Back', causes_path %>

app/views/causes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cause.name %>
</p>

<p>
  <b>Category:</b>
  <%= @cause.category_id %>
</p>


<%= link_to 'Edit', edit_cause_path(@cause) %> |
<%= link_to 'Back', causes_path %>