config/routes.rb
Chabad::Application.routes.draw do
  get "pages/performing_art_for_all"

 devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
 resources :causes
 resources :donations do
  collection do
    get 'express_paypal'    
    get 'pay'
  end  
 end

  root :to => 'home#index'

end

app/views/shared/_error_messages.html.erb
<% if target && target.errors.any? %>
  <div id="errorExplanation" class="errorExplanation" data-hook>
    <h2><%= t(:errors_prohibited_this_record_from_being_saved, :count => target.errors.count) %>:</h2>
    <p><%= t(:there_were_problems_with_the_following_fields) %>:</p>
     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name != :timedout %>
    <div class="alert alert-<%= name == :notice ? 'success' : 'error'%>">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  Developed by <a href='http://www.smartsoftasia.com' title='SmartSoftAsia - Custom Software Development' target="_blank">SmartSoftAsia</a>
</div>

app/views/shared/_head.html.erb
<title>Friends Of The Arts</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if gte IE 9]>
  <style type="text/css">
    .gradient {
       filter: none;
    }
  </style>
<![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45691753-1', 'friends-of-the-arts.info');
  ga('send', 'pageview');

</script>

app/views/shared/_header.html.erb
<div id="header" role="header">
  <div class="container-fluid">
    <div class="row-fluid">
      <div id="logo" class="pull-left"><%= link_to image_tag("logo.png"), "/" %></div>
      <div id="smart-logo">
        Developed by
        <%= link_to image_tag("smart-logo.png", id: "smart-logo"), "http://www.smartsoftasia.com"%>
      </div>
      <% if current_user %>
      <div class="pull-right sidebar">
        <ul class="user-panel">
          <% if current_user.admin %>
            <li>
              <%= link_to 'Donations', donations_path %>
            </li>            
            <li class="divider"> | </li>
          <% end %>
          <li>
            <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>        
          </li>
        </ul>
      </div>
    <% end %>  
    </div>
    <div class="row-fluid">
      <%= render 'shared/flash_messages' %>
    </div>
  </div>
</div>

app/views/shared/_header_back_up.html.erb
<header class="navbar">
  <nav class="navbar-inner">
    <div class="container">
<%= link_to image_tag("gallery.png", :size => '150x60'), root_path, :class => 'brand', :style => 'text-align:center;' %>
      <div class="nav-collapse">
        <ul class="nav pull-right" style="margin: 15px">
          <% if user_signed_in? %>
            <% if current_user.admin %>
              <li>
                <%= link_to 'Donations', donations_path %>
              </li>
            <% end %>
            <li>
              <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>