config/routes.rb
Chabad::Application.routes.draw do
  get "pages/performing_art_for_all"

 devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
 devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end
 resources :causes
 resources :donations do
  collection do
    get 'express_paypal'    
    get 'pay'
  end  
 end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#before_filter :authenticate_user!
  require 'open-uri'
  def index
    # sign_out(current_user) if user_signed_in? && !current_user.admin

  	#@img=""
  	#if !current_user.uid.blank?
    #  @img="http://graph.facebook.com/#{current_user.uid}/picture"
    	#end
    @donations = {}
    donations = Donation.order('pixel_id asc').includes(:user, :cause)
    
    pictures = {}
    facebook_ids = donations.map{|e| e.user[:facebook_id]}.compact.join(',')
    unless facebook_ids.blank?
      doc = Nokogiri::HTML(open("https://graph.facebook.com/?ids=#{facebook_ids}&fields=picture&return_ssl_resources=true"))
      pictures = JSON.parse(doc)
    end
    donations.each do |d| 
    	donation = {}
    	donation["user"] = d.anonymous ? "Anonymous" : d.user.full_name
      donation["anonymous"] = d.anonymous
    	donation["cause"] = d.cause.try(:name)
    	donation["facebook_id"] = d.user.facebook_id
      if pictures[d.user.facebook_id] && pictures[d.user.facebook_id]["picture"].present?
        begin
          donation["picture"] = pictures[d.user.facebook_id]["picture"]["data"]["url"]
        rescue
          next
        end
      end
    	@donations[d.pixel_id]=donation
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="background">
	<div class="row-fluid">
		<div class="span12">
			<div class="row-fluid">
				<div class="span7 video">
					<iframe width="530" height="298" src="https://www.youtube.com/embed/WQZlE3Iy7mI?showinfo=0" frameborder="0" allowfullscreen></iframe>
				</div>
				<div class="span5">
							<h2>Your donation will help us !</h2>
							<p>Make a donation to the friends-of-the-Arts foundation and help ‘talented’ students achieve their dreams through furthering their education under the tutelage of professional and experienced teachers and mentors.<p></p>Please select the type of donation you wish to make:</p>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span12 head">
						<h2>Scholarship Program</h2>
						<p>The foundation aims to award grant / bursaries for:</p>
						<p>- 12 Thai scholarship program 2014 (150,000 THB each)</p>
						<p>- 1 student will be selected in 2014 for further education abroad on the international scholarship program starting in 2015!</p>

						<h2>Connecting ASEAN Community Program</h2>
						<p>The foundation aims to award grant / bursaries for:</p>
						<p>- Tuition is valued at 50,000 Baht for one student to attend 10 day program!</p>
						<p>- There are also ‘funds’ available for students from overseas who need assistance for travel / accommodation / per-diem for food </p>
						
						<p>To make a donation with facebook's ID. Please click on the blocks below or <%= link_to "make a donation here", new_donation_path %> if you do not prefer to use facebook's ID.</p>
					</div>
				</div>
			</div>
		</div>		
		<div class="row-fluid">
			<div class="span12">
				<div class="gallery-background">
					<div class="gallery-container">
						<% 250.times do |pos| %>
						  <% if @donations[pos] %>
								<div class="box transparent box-donation" id='<%= "donation_#{pos}" %>' rel="tooltip" title="<%= "<p class='tooltip-content'>#{image_tag(@donations[pos]["picture"], :class => 'pull-left') if !@donations[pos]["anonymous"] && @donations[pos]["picture"].present? }#{@donations[pos]["user"]} - #{@donations[pos]["cause"]}</p>" %>">
								</div>
					    <% else %>
					      <div class="box empty" onclick="window.location.href='<%= user_signed_in? ? new_donation_path(:slot=>pos) : user_omniauth_authorize_path(:facebook,:slot=>pos) %>'">
					      </div>
					     <% end %>
					  <% end %>
					</div>
				</div>
			</div>
		</div>
	</div>